pull_request_rules:
  - name: Automatic merge on all check pass
    conditions:
      - author=KEINOS
      - base=master
      - title~=^Changes
      - and:
        - files=VERSION_SQLite3.txt
        - files=SQLite3-shields.io-badge.json
      - "#files=2"
      - check-success="Grype Container Scan / grype"
      - check-success="Snyk Docker Scan / snyk"
      - check-success="Code scanning results / Grype"
      - check-success="Code scanning results / Snyk Container"
    actions:
      merge:
        method: merge
