pull_request_rules:
  - name: Automatic merge on all check pass
    conditions:
      - author=KEINOS
      - base=master
      - title~=^Changes
      - and:
        - files=VERSION_SQLite3.txt
        - files=SQLite3-shields.io-badge.json
      - "#files=2"
      - check-success="grype"
      - check-success="snyk"
      - check-success="Snyk Container"
      - check-success="Grype"
    actions:
      merge:
        method: merge
