# =============================================================================
#  Container Scan with Grype
# =============================================================================
name: Grype Container Scan

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 00:45 UTC on Sunday (JST: AM 05:45 on every Monday)
    - cron: '45 0 * * 0'

jobs:
  grype:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Due to the deprecation of DOCKER_CONTENT_TRUST we removed the usage of
      # DOCKER_CONTENT_TRUST=1.
      # See: https://www.docker.com/blog/retiring-docker-content-trust/
      - name: Pre pull alpine image for stability
        run : docker pull alpine:latest

      - name: Build a Docker image
        run: docker build -t keinos/sqlite3:test .

      - name: Scan image
        id: scan
        uses: anchore/scan-action@v3
        with:
          image: "keinos/sqlite3:test"
          only-fixed: "true"

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}